import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import type {
  IntentLayerLanguage,
  IntentLayerSettings,
  IntentSetupRequest,
  IntentSetupResult,
  IntentSetupStatus
} from "./types";

export interface IntentWorkspaceInitResult {
  createdPaths: string[];
  existingPaths: string[];
}

function toSlashPath(value: string): string {
  return value.replace(/\\/g, "/");
}

function relativeFromRoot(rootDir: string, file: string): string {
  return toSlashPath(path.relative(rootDir, file));
}

function settingsPath(rootDir: string): string {
  return path.join(rootDir, ".intent", "settings.json");
}

function normalizeLanguage(language: unknown): IntentLayerLanguage {
  return language === "ko" ? "ko" : "en";
}

function writeFileIfMissing(
  rootDir: string,
  file: string,
  contents: string,
  createdPaths: string[],
  existingPaths: string[]
) {
  if (fs.existsSync(file)) {
    existingPaths.push(relativeFromRoot(rootDir, file));
    return;
  }

  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, contents);
  createdPaths.push(relativeFromRoot(rootDir, file));
}

function createDirIfMissing(rootDir: string, dir: string, createdPaths: string[], existingPaths: string[]) {
  if (fs.existsSync(dir)) {
    existingPaths.push(relativeFromRoot(rootDir, dir));
    return;
  }

  fs.mkdirSync(dir, { recursive: true });
  createdPaths.push(relativeFromRoot(rootDir, dir));
}

export function initIntentWorkspace(rootDir: string): IntentWorkspaceInitResult {
  const createdPaths: string[] = [];
  const existingPaths: string[] = [];
  const intentDir = path.join(rootDir, ".intent");

  for (const dir of [
    intentDir,
    path.join(intentDir, "components"),
    path.join(intentDir, "operations"),
    path.join(intentDir, "diffs"),
    path.join(intentDir, "agent"),
    path.join(intentDir, "schema")
  ]) {
    createDirIfMissing(rootDir, dir, createdPaths, existingPaths);
  }

  writeFileIfMissing(
    rootDir,
    path.join(intentDir, "README.md"),
    [
      "# INTENT_LAYER Workspace",
      "",
      "Generated by Intent Layer setup.",
      "",
      "- `graph.intent.json`: latest source binding graph",
      "- `components/`: optional component intent documents",
      "- `operations/`: deterministic patch operations",
      "- `diffs/`: semantic intent diffs",
      "- `agent/`: AI handoff tasks and results",
      "- `schema/`: lightweight format contracts",
      ""
    ].join("\n"),
    createdPaths,
    existingPaths
  );

  writeFileIfMissing(
    rootDir,
    path.join(intentDir, "schema", "intent-op.schema.json"),
    `${JSON.stringify(
      {
        version: 1,
        kind: "intent-op.schema",
        required: ["version", "kind", "target", "change"],
        supportedKinds: ["tailwind-token-replace"],
        target: {
          required: ["id"],
          optional: ["componentName", "file", "tagName", "range"]
        },
        change: {
          required: ["from", "to"]
        }
      },
      null,
      2
    )}\n`,
    createdPaths,
    existingPaths
  );

  writeFileIfMissing(
    rootDir,
    path.join(intentDir, "schema", "intent-diff.schema.json"),
    `${JSON.stringify(
      {
        version: 1,
        kind: "intent-diff.schema",
        required: ["version", "kind", "createdAt", "changes"],
        note: "MVP diffs are YAML files with deterministic source/semantic change summaries."
      },
      null,
      2
    )}\n`,
    createdPaths,
    existingPaths
  );

  writeFileIfMissing(
    rootDir,
    path.join(intentDir, "schema", "graph.intent.schema.json"),
    `${JSON.stringify(
      {
        version: 1,
        kind: "graph.intent.schema",
        required: ["version", "generatedAt", "entries"],
        entry: {
          required: ["id", "file", "relativeFile", "sourceHash", "className", "tokens"]
        }
      },
      null,
      2
    )}\n`,
    createdPaths,
    existingPaths
  );

  return { createdPaths, existingPaths };
}

export function readIntentSettings(rootDir: string): IntentLayerSettings | null {
  const file = settingsPath(rootDir);
  if (!fs.existsSync(file)) return null;

  try {
    const parsed = JSON.parse(fs.readFileSync(file, "utf8")) as Partial<IntentLayerSettings>;
    return {
      version: 1,
      language: normalizeLanguage(parsed.language),
      onboardingCompletedAt:
        typeof parsed.onboardingCompletedAt === "string" ? parsed.onboardingCompletedAt : null
    };
  } catch {
    return null;
  }
}

function writeIntentSettings(
  rootDir: string,
  settings: IntentLayerSettings,
  createdPaths: string[],
  existingPaths: string[]
): string {
  const file = settingsPath(rootDir);
  const existed = fs.existsSync(file);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify(settings, null, 2)}\n`);
  (existed ? existingPaths : createdPaths).push(relativeFromRoot(rootDir, file));
  return relativeFromRoot(rootDir, file);
}

function executableAvailable(command: string, rootDir: string): boolean {
  if (path.isAbsolute(command) || command.includes("/") || command.includes("\\")) {
    return fs.existsSync(command);
  }

  const checker = process.platform === "win32" ? "where.exe" : "which";
  const result = spawnSync(checker, [command], {
    cwd: rootDir,
    stdio: "ignore"
  });
  return result.status === 0;
}

export function intentSetupStatus(
  rootDir: string,
  options: { graphEntryCount?: number; language?: IntentLayerLanguage } = {}
): IntentSetupStatus {
  const settings = readIntentSettings(rootDir);
  const language = options.language ?? settings?.language ?? "en";
  const intentDir = path.join(rootDir, ".intent");
  const workspaceReady =
    fs.existsSync(intentDir) &&
    fs.existsSync(path.join(intentDir, "schema", "graph.intent.schema.json")) &&
    fs.existsSync(path.join(intentDir, "schema", "intent-op.schema.json")) &&
    fs.existsSync(path.join(intentDir, "schema", "intent-diff.schema.json"));
  const settingsReady = Boolean(settings?.onboardingCompletedAt);
  const graphEntryCount = options.graphEntryCount ?? 0;
  const graphReady = graphEntryCount > 0 || fs.existsSync(path.join(intentDir, "graph.intent.json"));
  const codexCommand = process.env.INTENT_LAYER_CODEX_COMMAND?.trim() || "codex";
  const claudeCommand = process.env.INTENT_LAYER_CLAUDE_COMMAND?.trim() || "claude";

  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    root: rootDir,
    language,
    workspaceReady,
    settingsReady,
    graphReady,
    graphEntryCount,
    setupRequired: !workspaceReady || !settingsReady,
    checks: [
      {
        name: "workspace",
        status: workspaceReady ? "ready" : "missing",
        detail: workspaceReady ? ".intent workspace is ready." : ".intent workspace has not been created yet."
      },
      {
        name: "language",
        status: settingsReady ? "ready" : "warn",
        detail: `Overlay language: ${language === "ko" ? "Korean" : "English"}.`
      },
      {
        name: "graph",
        status: graphReady ? "ready" : "warn",
        detail: graphReady
          ? `${graphEntryCount} source bindings are available.`
          : "Source bindings will appear after Vite transforms JSX/TSX files."
      },
      {
        name: "agent-run",
        status: process.env.INTENT_LAYER_AGENT_RUN === "1" ? "ready" : "warn",
        detail:
          process.env.INTENT_LAYER_AGENT_RUN === "1"
            ? "Agent run is enabled. Run buttons may spawn local CLIs."
            : "Agent run is locked. Run buttons will show command plans until INTENT_LAYER_AGENT_RUN=1 is set."
      }
    ],
    agent: {
      runEnabled: process.env.INTENT_LAYER_AGENT_RUN === "1",
      codexCommand,
      codexAvailable: executableAvailable(codexCommand, rootDir),
      claudeCommand,
      claudeAvailable: executableAvailable(claudeCommand, rootDir)
    }
  };
}

export function applyIntentSetup(
  rootDir: string,
  request: IntentSetupRequest,
  options: { graphEntryCount?: number } = {}
): IntentSetupResult {
  const started = performance.now();
  const createdPaths: string[] = [];
  const existingPaths: string[] = [];

  if (request.createWorkspace !== false) {
    const init = initIntentWorkspace(rootDir);
    createdPaths.push(...init.createdPaths);
    existingPaths.push(...init.existingPaths);
  }

  const previous = readIntentSettings(rootDir);
  const language = normalizeLanguage(request.language ?? previous?.language ?? "en");
  const settingsFile = writeIntentSettings(
    rootDir,
    {
      version: 1,
      language,
      onboardingCompletedAt:
        request.completeOnboarding === false
          ? previous?.onboardingCompletedAt ?? null
          : previous?.onboardingCompletedAt ?? new Date().toISOString()
    },
    createdPaths,
    existingPaths
  );

  return {
    ok: true,
    status: intentSetupStatus(rootDir, {
      graphEntryCount: options.graphEntryCount,
      language
    }),
    createdPaths,
    existingPaths,
    settingsFile,
    metrics: {
      setupMs: Number((performance.now() - started).toFixed(3))
    }
  };
}
